name: 04 - Listar arquivos
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listar arquivos
        run: ls -la
