name: 11 - Stats do push (único step)
on:
  push:
    branches: [ "main" ]

jobs:
  stats_single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tudo de uma vez
        shell: bash
        run: |
          set -euo pipefail

          echo "Agora (UTC): $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "github.actor: ${{ github.actor }}"

          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          if [ -n "$BEFORE" ] && [ "$BEFORE" != "0000000000000000000000000000000000000000" ]; then
            git diff --name-only "$BEFORE" "$AFTER" > changed.txt || true
          else
            git show --name-only --pretty="" "$AFTER" > changed.txt || true
          fi

          tr -d '\r' < changed.txt > changed.clean && mv changed.clean changed.txt

          html=$(grep -E -c '\.html$' changed.txt || true)
          css=$(grep -E -c '\.css$'  changed.txt || true)
          js=$(grep -E -c '\.js$'    changed.txt || true)

          echo "Arquivos alterados:"
          cat changed.txt || true
          echo "HTML: $html | CSS: $css | JS: $js"
